# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/14017/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-3228-LAPTOP-8FN33LQG/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/FPGA/FIFO/FIFO.cache/wt [current_project]
set_property parent.project_path F:/FPGA/FIFO/FIFO.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/FPGA/FIFO/FIFO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/FPGA/FIFO/FIFO.srcs/sources_1/new/fifo.v
read_ip -quiet f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/fifo_ip/fifo_ip.xci
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/fifo_ip/fifo_ip.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/fifo_ip/fifo_ip_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/fifo_ip/fifo_ip_ooc.xdc]

read_ip -quiet f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all f:/FPGA/FIFO/FIFO.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/FPGA/FIFO/FIFO.srcs/constrs_1/new/fifo.xdc
set_property used_in_implementation false [get_files F:/FPGA/FIFO/FIFO.srcs/constrs_1/new/fifo.xdc]


synth_design -top fifo -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fifo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fifo_utilization_synth.rpt -pb fifo_utilization_synth.pb"
